-- The sqlide demo database, PostgreSQL dialect.
--
-- Two ways in, both reading this one file:
--   * docker-compose.yml mounts it into the container's
--     /docker-entrypoint-initdb.d, so a fresh server has it at first
--     start;
--   * scripts/init_databases.py replays it against servers that are
--     already running (it understands CREATE DATABASE and \connect,
--     and runs everything else as SQL).
--
-- It lives in its own database, `demo`, so it never collides with
-- `sqlide`, the database the tests reseed.
--
-- The schema is the same shape on every engine and deliberately shows
-- the cases sqlide has to handle: a table with a primary key (editable
-- rows), one without (read-only), a view, an index, a trigger and a
-- stored function (the sidebar categories), and a foreign key (the
-- relation graph).

CREATE DATABASE demo;
\connect demo

CREATE TABLE customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text,
    city text
);

CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id),
    item text NOT NULL,
    amount numeric(10, 2) NOT NULL,
    placed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_orders_customer ON orders (customer_id);

-- No primary key on purpose: sqlide shows this one read-only.
CREATE TABLE log (
    at timestamptz DEFAULT now(),
    message text
);

CREATE VIEW order_totals AS
SELECT c.name, count(o.id) AS orders, coalesce(sum(o.amount), 0) AS total
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id
GROUP BY c.id, c.name;

CREATE FUNCTION customer_total(customer integer) RETURNS numeric AS $$
    SELECT coalesce(sum(amount), 0) FROM orders WHERE customer_id = customer;
$$ LANGUAGE sql;

CREATE FUNCTION log_order() RETURNS trigger AS $$
BEGIN
    INSERT INTO log (message) VALUES ('order ' || NEW.id || ' placed');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- EXECUTE PROCEDURE, not EXECUTE FUNCTION: the compose file goes back
-- to PostgreSQL 10, which has only the older spelling (still accepted
-- by every later version).
CREATE TRIGGER orders_logged
AFTER INSERT ON orders
FOR EACH ROW EXECUTE PROCEDURE log_order();

INSERT INTO customers (id, name, email, city) VALUES
    (1, 'Ada Lovelace', 'ada@example.com', 'London'),
    (2, 'Alan Turing', 'alan@example.com', 'Manchester'),
    (3, 'Grace Hopper', 'grace@example.com', 'New York'),
    (4, 'Edsger Dijkstra', NULL, 'Nuenen');

INSERT INTO orders (customer_id, item, amount) VALUES
    (1, 'Analytical Engine plans', 120.00),
    (1, 'Punch cards (box)', 9.50),
    (2, 'Enigma replica', 300.00),
    (3, 'COBOL manual', 25.00),
    (3, 'Compiler license', 199.99);

-- The rows above carry their own ids, which leaves the identity
-- sequences behind; move them past the seeded data so the next insert
-- does not collide.
SELECT setval(pg_get_serial_sequence('customers', 'id'), 4);
SELECT setval(pg_get_serial_sequence('orders', 'id'), 5);
