"""The table model, its DDL renderer and its planner (CORE-23).

Everything here runs against a `Dialect` rather than a connector, so
no test in this file opens a database.
"""

from dataclasses import replace

import pytest

from sqlide.backend.db.table_model import (
    MYSQL,
    POSTGRES,
    SQLITE,
    ColumnDefault,
    ColumnModel,
    ConstraintModel,
    IndexModel,
    TableModel,
    TableModelError,
    dump_state,
    from_dict,
    load_state,
    plan,
    render_comments,
    render_create,
    render_indexes,
    to_dict,
    worst,
)


def _people(**kwargs) -> TableModel:
    return TableModel(
        name="people",
        columns=(
            ColumnModel("id", "INTEGER", nullable=False, primary_key=True),
            ColumnModel("name", "TEXT", nullable=False),
            ColumnModel(
                "bio", "TEXT", default=ColumnDefault("literal", "hello")
            ),
        ),
        **kwargs,
    )


# Rendering


def test_render_create_sqlite():
    assert render_create(_people(), SQLITE) == (
        'CREATE TABLE "people" (\n'
        '  "id" INTEGER NOT NULL,\n'
        '  "name" TEXT NOT NULL,\n'
        "  \"bio\" TEXT DEFAULT 'hello',\n"
        '  PRIMARY KEY ("id")\n'
        ")"
    )


def test_render_create_quotes_per_dialect():
    sql = render_create(_people(), MYSQL)
    assert "`people`" in sql and '`id` INTEGER NOT NULL' in sql
    assert '"' not in sql


def test_render_create_qualifies_schema_only_where_there_are_schemas():
    model = TableModel(
        name="people", schema="crm", columns=(ColumnModel("id", "INT"),)
    )
    assert render_create(model, POSTGRES).startswith(
        'CREATE TABLE "crm"."people"'
    )
    # MySQL and SQLite have no schema level; the name stays bare.
    assert render_create(model, MYSQL).startswith("CREATE TABLE `people`")


def test_composite_primary_key():
    model = TableModel(
        name="pair",
        columns=(
            ColumnModel("a", "INT", nullable=False, primary_key=True),
            ColumnModel("b", "INT", nullable=False, primary_key=True),
        ),
    )
    assert '  PRIMARY KEY ("a", "b")' in render_create(model, POSTGRES)


def test_primary_key_from_a_constraint():
    model = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT", nullable=False),),
        constraints=(ConstraintModel("PRIMARY KEY", columns=("a",)),),
    )
    assert '  PRIMARY KEY ("a")' in render_create(model, POSTGRES)


def test_default_literal_versus_expression():
    literal = ColumnModel("t", "TEXT", default=ColumnDefault("literal", "it's"))
    expr = ColumnModel("t", "TEXT", default=ColumnDefault("expression", "now()"))
    number = ColumnModel("t", "INT", default=ColumnDefault("literal", "42"))
    none = ColumnModel("t", "TEXT")
    model = lambda c: TableModel(name="x", columns=(c,))  # noqa: E731
    assert "DEFAULT 'it''s'" in render_create(model(literal), POSTGRES)
    assert "DEFAULT now()" in render_create(model(expr), POSTGRES)
    assert "DEFAULT 42" in render_create(model(number), POSTGRES)
    assert "DEFAULT" not in render_create(model(none), POSTGRES)


def test_default_keyword_literal_is_not_quoted():
    assert ColumnDefault("literal", "current_timestamp").render() == (
        "CURRENT_TIMESTAMP"
    )
    assert ColumnDefault("none", "x").render() == ""


def test_identity_is_spelled_per_dialect():
    model = TableModel(
        name="t",
        columns=(
            ColumnModel(
                "id", "INTEGER", nullable=False, primary_key=True, identity=True
            ),
        ),
    )
    assert "GENERATED BY DEFAULT AS IDENTITY" in render_create(model, POSTGRES)
    assert "AUTO_INCREMENT" in render_create(model, MYSQL)
    sqlite = render_create(model, SQLITE)
    assert "PRIMARY KEY AUTOINCREMENT" in sqlite
    # SQLite's rowid alias is the key; a second table-level clause
    # would be a syntax error.
    assert sqlite.count("PRIMARY KEY") == 1


def test_comments_inline_on_mysql_and_separate_on_postgres():
    model = TableModel(
        name="t",
        comment="people",
        columns=(ColumnModel("a", "INT", comment="an a"),),
    )
    assert "COMMENT 'an a'" in render_create(model, MYSQL)
    assert render_comments(model, MYSQL) == []
    assert render_comments(model, POSTGRES) == [
        "COMMENT ON TABLE \"t\" IS 'people'",
        "COMMENT ON COLUMN \"t\".\"a\" IS 'an a'",
    ]
    assert render_comments(model, SQLITE) == []


def test_constraints_render():
    model = TableModel(
        name="orders",
        columns=(ColumnModel("id", "INT"), ColumnModel("customer", "INT")),
        constraints=(
            ConstraintModel("UNIQUE", name="orders_id", columns=("id",)),
            ConstraintModel("CHECK", expression="id > 0"),
            ConstraintModel(
                "FOREIGN KEY",
                name="orders_customer",
                columns=("customer",),
                ref_table="customers",
                ref_columns=("id",),
                on_delete="cascade",
            ),
        ),
    )
    sql = render_create(model, POSTGRES)
    assert '  CONSTRAINT "orders_id" UNIQUE ("id")' in sql
    assert "  CHECK (id > 0)" in sql
    assert (
        '  CONSTRAINT "orders_customer" FOREIGN KEY ("customer") '
        'REFERENCES "customers" ("id") ON DELETE CASCADE' in sql
    )


def test_table_options_per_dialect():
    mysql = render_create(
        TableModel(
            name="t",
            columns=(ColumnModel("a", "INT"),),
            options={"ENGINE": "InnoDB"},
        ),
        MYSQL,
    )
    assert mysql.endswith(") ENGINE=InnoDB")
    sqlite = render_create(
        TableModel(
            name="t",
            columns=(ColumnModel("a", "INT"),),
            options={"WITHOUT ROWID": "true"},
        ),
        SQLITE,
    )
    assert sqlite.endswith(") WITHOUT ROWID")


def test_generated_columns_only_where_the_engine_has_them():
    model = TableModel(
        name="t",
        columns=(
            ColumnModel("a", "INT"),
            ColumnModel("b", "INT", generated="a * 2"),
        ),
    )
    assert "GENERATED ALWAYS AS (a * 2) STORED" in render_create(model, MYSQL)
    # PostgreSQL 10 and SQLite 3.25 — our floors — have none.
    assert "GENERATED ALWAYS" not in render_create(model, POSTGRES)


def test_index_rendering():
    model = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"),),
        indexes=(
            IndexModel(name="t_a", columns=("a",)),
            IndexModel(name="t_a_u", columns=("a",), unique=True, method="hash"),
        ),
    )
    assert render_indexes(model, POSTGRES) == [
        'CREATE INDEX "t_a" ON "t" ("a")',
        'CREATE UNIQUE INDEX "t_a_u" ON "t" USING hash ("a")',
    ]
    # SQLite has no access-method clause; the index is still created.
    assert 'USING' not in render_indexes(model, SQLITE)[1]


def test_bad_models_are_refused_not_rendered():
    with pytest.raises(TableModelError):
        render_create(TableModel(name="", columns=(ColumnModel("a"),)), POSTGRES)
    with pytest.raises(TableModelError):
        render_create(TableModel(name="t"), POSTGRES)
    with pytest.raises(TableModelError):
        render_create(
            TableModel(
                name="t",
                columns=(ColumnModel("a", "INT"),),
                constraints=(ConstraintModel("CHECK"),),
            ),
            POSTGRES,
        )


def test_quoting_escapes_the_quote_character():
    model = TableModel(name='we"ird', columns=(ColumnModel('a"b', "INT"),))
    assert 'CREATE TABLE "we""ird"' in render_create(model, POSTGRES)
    assert '"a""b" INT' in render_create(model, POSTGRES)
    assert "`a\"b` INT" in render_create(model, MYSQL)


# Serialisation


def test_json_round_trip():
    model = TableModel(
        name="orders",
        schema="crm",
        comment="the orders",
        options={"ENGINE": "InnoDB"},
        columns=(
            ColumnModel(
                "id",
                "INT",
                nullable=False,
                primary_key=True,
                identity=True,
                comment="key",
                options={"unsigned": "yes"},
            ),
            ColumnModel(
                "total", "NUMERIC(10,2)", default=ColumnDefault("literal", "0")
            ),
        ),
        constraints=(
            ConstraintModel(
                "FOREIGN KEY",
                name="fk",
                columns=("id",),
                ref_table="c",
                ref_columns=("id",),
                on_delete="CASCADE",
            ),
        ),
        indexes=(IndexModel(name="i", columns=("total",), unique=True),),
    )
    assert from_dict(to_dict(model)) == model
    assert load_state(dump_state(model)) == model


def test_load_state_is_unexcitable():
    assert load_state("") is None
    assert load_state("not json") is None
    assert load_state("[]") is None
    assert load_state('{"version": 99, "model": {}}') is None
    assert load_state('{"version": 1}') is None
    assert load_state('{"version": 1, "model": {}}') == TableModel()


# Planning


def test_plan_for_a_create_is_one_create_plus_its_indexes():
    model = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"),),
        indexes=(IndexModel(name="t_a", columns=("a",)),),
    )
    statements = plan(None, model, POSTGRES)
    assert [s.classification for s in statements] == ["safe", "safe"]
    assert statements[0].sql.startswith("CREATE TABLE")
    assert statements[1].sql.startswith("CREATE INDEX")
    assert worst(statements) == "safe"


def test_plan_classifies_a_safe_add():
    current = TableModel(name="t", columns=(ColumnModel("a", "INT"),))
    target = TableModel(
        name="t", columns=(ColumnModel("a", "INT"), ColumnModel("b", "TEXT"))
    )
    (statement,) = plan(current, target, POSTGRES)
    assert statement.classification == "safe"
    assert statement.sql == 'ALTER TABLE "t" ADD COLUMN "b" TEXT'


def test_plan_classifies_a_may_fail_not_null_add():
    current = TableModel(name="t", columns=(ColumnModel("a", "INT"),))
    target = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"), ColumnModel("b", "TEXT", nullable=False)),
    )
    (statement,) = plan(current, target, POSTGRES)
    assert statement.classification == "may_fail"
    assert "fails if the table has rows" in statement.note


def test_plan_classifies_a_rewrite_type_change():
    current = TableModel(name="t", columns=(ColumnModel("a", "INT"),))
    target = TableModel(name="t", columns=(ColumnModel("a", "BIGINT"),))
    (statement,) = plan(current, target, POSTGRES)
    assert statement.classification == "rewrite"
    assert statement.sql == 'ALTER TABLE "t" ALTER COLUMN "a" TYPE BIGINT'


def test_plan_classifies_a_destructive_drop():
    current = TableModel(
        name="t", columns=(ColumnModel("a", "INT"), ColumnModel("b", "INT"))
    )
    target = TableModel(name="t", columns=(ColumnModel("a", "INT"),))
    (statement,) = plan(current, target, POSTGRES)
    assert statement.classification == "destructive"
    assert statement.sql == 'ALTER TABLE "t" DROP COLUMN "b"'
    assert worst([statement]) == "destructive"


def test_plan_tightening_nullability_may_fail():
    current = TableModel(name="t", columns=(ColumnModel("a", "INT"),))
    target = TableModel(
        name="t", columns=(ColumnModel("a", "INT", nullable=False),)
    )
    (statement,) = plan(current, target, POSTGRES)
    assert statement.classification == "may_fail"
    assert statement.sql.endswith("SET NOT NULL")
    # And loosening it is safe.
    (back,) = plan(target, current, POSTGRES)
    assert back.classification == "safe"
    assert back.sql.endswith("DROP NOT NULL")


def test_plan_restates_the_whole_column_on_mysql():
    current = TableModel(name="t", columns=(ColumnModel("a", "INT"),))
    target = TableModel(name="t", columns=(ColumnModel("a", "BIGINT"),))
    (statement,) = plan(current, target, MYSQL)
    assert statement.sql == "ALTER TABLE `t` MODIFY COLUMN `a` BIGINT"


def test_plan_diffs_constraints_and_indexes():
    current = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"),),
        constraints=(ConstraintModel("UNIQUE", name="old", columns=("a",)),),
    )
    target = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"),),
        constraints=(ConstraintModel("CHECK", name="new", expression="a > 0"),),
        indexes=(IndexModel(name="i", columns=("a",), unique=True),),
    )
    kinds = {s.sql: s.classification for s in plan(current, target, POSTGRES)}
    assert kinds['ALTER TABLE "t" DROP CONSTRAINT "old"'] == "safe"
    assert (
        kinds['ALTER TABLE "t" ADD CONSTRAINT "new" CHECK (a > 0)'] == "may_fail"
    )
    assert kinds['CREATE UNIQUE INDEX "i" ON "t" ("a")'] == "may_fail"


def test_plan_renames_the_table():
    current = TableModel(name="old", columns=(ColumnModel("a", "INT"),))
    target = TableModel(name="new", columns=(ColumnModel("a", "INT"),))
    (statement,) = plan(current, target, POSTGRES)
    assert statement.sql == 'ALTER TABLE "old" RENAME TO "new"'
    assert statement.classification == "safe"


def test_plan_falls_back_to_a_rebuild_on_sqlite():
    current = TableModel(
        name="t", columns=(ColumnModel("a", "INT"), ColumnModel("b", "TEXT"))
    )
    target = TableModel(name="t", columns=(ColumnModel("a", "BIGINT"),))
    statements = plan(current, target, SQLITE)
    sqls = [s.sql for s in statements]
    assert sqls[0] == 'ALTER TABLE "t" RENAME TO "t__sqlide_old"'
    assert sqls[1].startswith("CREATE TABLE")
    assert sqls[2] == (
        'INSERT INTO "t" ("a") SELECT "a" FROM "t__sqlide_old"'
    )
    assert sqls[3] == 'DROP TABLE "t__sqlide_old"'
    assert worst(statements) == "destructive"  # column b goes away


def test_plan_is_empty_when_nothing_changed():
    model = _people()
    assert plan(model, model, POSTGRES) == []


def test_every_constraint_kind_renders_on_every_dialect():
    """CORE-25: each kind, each dialect, no connection."""
    model = TableModel(
        name="orders",
        columns=(
            ColumnModel("id", "INT"),
            ColumnModel("code", "TEXT"),
            ColumnModel("customer", "INT"),
        ),
        constraints=(
            ConstraintModel(
                "PRIMARY KEY", name="orders_pk", columns=("id", "code")
            ),
            ConstraintModel("UNIQUE", name="orders_code", columns=("code",)),
            ConstraintModel("CHECK", name="orders_ck", expression="id > 0"),
            ConstraintModel(
                "FOREIGN KEY",
                name="orders_fk",
                columns=("customer",),
                ref_table="customers",
                ref_columns=("id",),
                on_delete="cascade",
                on_update="restrict",
            ),
        ),
    )
    for dialect, q in ((POSTGRES, '"'), (MYSQL, "`"), (SQLITE, '"')):
        sql = render_create(model, dialect)
        i, c, cu = (f"{q}id{q}", f"{q}code{q}", f"{q}customer{q}")
        assert f"CONSTRAINT {q}orders_pk{q} PRIMARY KEY ({i}, {c})" in sql
        assert f"CONSTRAINT {q}orders_code{q} UNIQUE ({c})" in sql
        assert f"CONSTRAINT {q}orders_ck{q} CHECK (id > 0)" in sql
        assert (
            f"CONSTRAINT {q}orders_fk{q} FOREIGN KEY ({cu}) REFERENCES "
            f"{q}customers{q} ({i}) ON DELETE CASCADE ON UPDATE RESTRICT"
            in sql
        )


def test_an_unnamed_primary_key_constraint_still_renders_bare():
    model = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"), ColumnModel("b", "INT")),
        constraints=(ConstraintModel("PRIMARY KEY", columns=("a", "b")),),
    )
    assert '  PRIMARY KEY ("a", "b")' in render_create(model, POSTGRES)


def test_a_dialect_without_a_kind_leaves_it_out():
    limited = replace(POSTGRES, constraint_kinds=("PRIMARY KEY", "UNIQUE"))
    model = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"),),
        constraints=(ConstraintModel("CHECK", expression="a > 0"),),
    )
    assert "CHECK" not in render_create(model, limited)


def test_index_columns_carry_a_direction():
    model = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"), ColumnModel("b", "INT")),
        indexes=(
            IndexModel(
                name="t_ab",
                columns=("a", "b"),
                directions=("DESC", ""),
            ),
        ),
    )
    assert render_indexes(model, POSTGRES) == [
        'CREATE INDEX "t_ab" ON "t" ("a" DESC, "b")'
    ]
    # An index that says nothing about direction renders as it always did.
    plain = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"),),
        indexes=(IndexModel(name="t_a", columns=("a",)),),
    )
    assert render_indexes(plain, POSTGRES) == ['CREATE INDEX "t_a" ON "t" ("a")']


def test_index_directions_round_trip():
    model = TableModel(
        name="t",
        columns=(ColumnModel("a", "INT"),),
        indexes=(
            IndexModel(name="t_a", columns=("a",), directions=("DESC",)),
        ),
    )
    assert from_dict(to_dict(model)).indexes[0].directions == ("DESC",)
