"""PostgreSQL adapter (psycopg v3).

Catalog queries go through pg_catalog / information_schema, scoped to
the schemas on the connection's search_path (excluding pg_catalog and
information_schema) so bare table names resolve the same way a plain
SELECT would. Identifiers are double-quoted; pagination is LIMIT/OFFSET.

Schemas. A PostgreSQL database holds many of them, and the app works
in one at a time: a profile's `schema`, when set, becomes the
connection's search_path, so the catalog, bare-name SELECTs and DDL
all agree on which `orders` is meant. Left empty, the server's own
search_path stands (usually "$user", public) and objects outside it
stay invisible — the schema dropdown is how you reach them.

Name resolution never trusts relname alone: two schemas on the
search_path may both hold an `orders`, so anything that turns a name
into one relation goes through to_regclass(), which applies exactly
the precedence rule a plain SELECT would. Listings that cannot do
that (list_tables) keep the first match in search_path order, for the
same reason.

One connection is shared by all of the app's worker threads, so every
statement is serialized behind a lock (like the SQLite and MySQL
adapters). autocommit is on: statements commit unless the user runs an
explicit BEGIN — matching the other adapters' isolation setup.

Programmable objects (the sidebar's Functions category and the
editable definition tab) cover all of PostgreSQL's: PL/pgSQL (and any
other language) functions, procedures and triggers. list_functions()
returns their names; get_ddl() reconstructs a runnable CREATE via
pg_get_functiondef / pg_get_triggerdef, so editing and re-saving a
PL/pgSQL body round-trips through the definition tab.
"""

from __future__ import annotations

import threading
from typing import Any

import psycopg
from psycopg.pq import TransactionStatus

from sqlide.backend.db.base import (
    ColumnInfo,
    Connector,
    ConnectorError,
    ConstraintInfo,
    FilterCondition,
    FunctionInfo,
    GrantScope,
    IndexInfo,
    ObjectSummary,
    PageCursor,
    PrivilegeInfo,
    RelationInfo,
    ResultSet,
    SortSpec,
    TableInfo,
    TableStats,
    TriggerInfo,
    TypeSpec,
    UserInfo,
)
from sqlide.backend.db.extensions import ExtensionState
from sqlide.backend.settings import session_time_zone

_TEMPLATES = {
    "table": (
        "-- New table: adjust the name and columns, then Run.\n"
        "CREATE TABLE table_name (\n"
        "  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
        "  name text NOT NULL,\n"
        "  created_at timestamptz DEFAULT now()\n"
        ");\n"
    ),
    "view": (
        "-- New view: adjust the name and the SELECT, then Run.\n"
        "CREATE VIEW view_name AS\n"
        "SELECT column_a, column_b\n"
        "FROM table_name;\n"
    ),
    "index": (
        "-- New index: adjust the name, table and columns, then Run.\n"
        "-- Add UNIQUE after CREATE for a unique index.\n"
        "CREATE INDEX index_name\n"
        "ON table_name (column_a);\n"
    ),
    "trigger": (
        "-- New trigger: a Postgres trigger calls a trigger function;\n"
        "-- adjust both names, the timing and the body, then Run.\n"
        "-- (PostgreSQL 10 needs EXECUTE PROCEDURE instead.)\n"
        "CREATE OR REPLACE FUNCTION trigger_name_fn()\n"
        "RETURNS trigger\n"
        "LANGUAGE plpgsql\n"
        "AS $$\n"
        "BEGIN\n"
        "  RETURN NEW;\n"
        "END;\n"
        "$$;\n"
        "\n"
        "CREATE TRIGGER trigger_name\n"
        "BEFORE INSERT ON table_name\n"
        "FOR EACH ROW\n"
        "EXECUTE FUNCTION trigger_name_fn();\n"
    ),
    "function": (
        "-- New function: adjust the name, arguments and body, then"
        " Run.\n"
        "CREATE OR REPLACE FUNCTION function_name(a integer, b integer)\n"
        "RETURNS integer\n"
        "LANGUAGE plpgsql\n"
        "AS $$\n"
        "BEGIN\n"
        "  RETURN a + b;\n"
        "END;\n"
        "$$;\n"
    ),
    "procedure": (
        "-- New procedure (PostgreSQL 11+): adjust the name, arguments\n"
        "-- and body, then Run. Call it with: CALL procedure_name(…);\n"
        "CREATE OR REPLACE PROCEDURE procedure_name(a integer)\n"
        "LANGUAGE plpgsql\n"
        "AS $$\n"
        "BEGIN\n"
        "  RAISE NOTICE 'got %', a;\n"
        "END;\n"
        "$$;\n"
    ),
}

# Schemas visible on the search_path but not user objects.
_SYSTEM_SCHEMAS = ("pg_catalog", "information_schema")

# The subset of the search_path we treat as "the user's schemas": the
# real (non-system) entries, e.g. public. Bare names in the app resolve
# against exactly these.
_USER_SCHEMAS = (
    "SELECT nspname FROM unnest(current_schemas(false)) AS nspname "
    "WHERE nspname NOT IN ('pg_catalog', 'information_schema')"
)

# Where a name sits in the search_path: 1 for the first schema, 2 for
# the next. Ties in a listing break toward the lower number, which is
# the schema an unqualified reference would actually hit.
_SEARCH_PATH_RANK = "array_position(current_schemas(false), n.nspname)"

# relkind -> the note a relation row carries when it is a special case
# of its kind. A plain table and a plain view say nothing; the three
# that behave differently — a partitioned table you can nest into, a
# foreign table that lives on another server, a materialized view that
# holds rows of its own — say which they are, so the tree distinguishes
# them without a second icon vocabulary (PG-02).
_RELKIND_DETAIL = {
    "p": "partitioned",
    "f": "foreign",
    "m": "materialized",
}


def _relation_detail(relkind: str, is_partition: bool) -> str:
    """A relation's note: "partition" wins over everything, because a
    partition is reached through the table it belongs to and a schema
    listing that repeats every one of them buries the tables people
    came for (PG-02)."""
    return "partition" if is_partition else _RELKIND_DETAIL.get(relkind, "")


class PostgresConnector(Connector):
    # psycopg binds with %s.
    placeholder = "%s"

    def __init__(
        self,
        host: str,
        port: int,
        user: str,
        password: str,
        database: str,
        schema: str = "",
        ssl: dict | None = None,
        ssh: dict | None = None,
    ) -> None:
        self.host = host
        self.port = port
        self.user = user
        self.password = password
        self.database = database
        self.schema = schema
        self.ssl = ssl
        self.ssh = ssh
        self._conn: psycopg.Connection | None = None
        self._tunnel = None  # sqlide.backend.ssh.SshTunnel when active
        self._lock = threading.Lock()

    def _ssl_kwargs(self) -> dict:
        """psycopg connect kwargs for the profile's SSL settings."""
        if not self.ssl:
            return {}
        kwargs: dict = {}
        mode = self.ssl.get("mode", "")
        if mode:
            kwargs["sslmode"] = mode
        if self.ssl.get("ca"):
            kwargs["sslrootcert"] = self.ssl["ca"]
        if self.ssl.get("cert"):
            kwargs["sslcert"] = self.ssl["cert"]
        if self.ssl.get("key"):
            kwargs["sslkey"] = self.ssl["key"]
        return kwargs

    def connect(self) -> None:
        self.invalidate_catalog()
        host, port = self.host, self.port
        if self.ssh:
            from sqlide.backend.ssh import SshTunnel

            self._tunnel = SshTunnel(
                host=self.ssh.get("host", ""),
                port=self.ssh.get("port", 22),
                user=self.ssh.get("user", ""),
                password=self.ssh.get("password", ""),
                key_path=self.ssh.get("key_path", ""),
                remote_host=self.host,
                remote_port=self.port,
            )
            try:
                port = self._tunnel.start()
            except Exception:
                self._tunnel = None
                raise
            host = "127.0.0.1"
        try:
            self._conn = psycopg.connect(
                host=host,
                port=port,
                user=self.user,
                password=self.password,
                dbname=self.database or None,
                autocommit=True,
                connect_timeout=10,
                **self._ssl_kwargs(),
            )
        except psycopg.Error as exc:
            self._stop_tunnel()
            raise ConnectorError(_message(exc)) from exc
        self._apply_time_zone()
        if self.schema:
            # One schema on the path, so every later query — catalog
            # lookups, bare-name SELECTs, CREATE without a qualifier —
            # lands in the schema the profile asked for. pg_catalog
            # stays implicitly first, as always.
            #
            # Checked first: SET search_path accepts a schema that does
            # not exist (the name is only resolved when something uses
            # it), and the result would be a connection that opens
            # fine and then shows an empty database with no reason
            # given. A typo should say so here.
            try:
                with self._conn.cursor() as cur:
                    cur.execute(
                        "SELECT 1 FROM pg_namespace WHERE nspname = %s",
                        (self.schema,),
                    )
                    exists = cur.fetchone() is not None
                if not exists:
                    raise ConnectorError(
                        f"No schema named {self.schema!r} in database "
                        f"{self.database!r}"
                    )
                self._conn.execute(
                    f"SET search_path TO {self.quote_ident(self.schema)}"
                )
            except psycopg.Error as exc:
                self.close()
                raise ConnectorError(_message(exc)) from exc
            except ConnectorError:
                self.close()
                raise

    def _apply_time_zone(self) -> None:
        """Pin the session's zone, so a timestamptz reads the same
        against every server instead of following whichever TimeZone
        the server happens to be configured with.

        Best-effort: a server that rejects the name (an unusual
        zoneinfo build) keeps its own setting rather than failing the
        whole connection.
        """
        zone = session_time_zone()
        if zone is None:
            return
        try:
            # set_config() rather than SET TIME ZONE: a utility
            # statement takes no parameters, and the zone name is not
            # ours to interpolate.
            self._conn.execute(
                "SELECT set_config('TimeZone', %s, false)", (zone,)
            )
        except psycopg.Error:
            pass

    def close(self) -> None:
        self.invalidate_catalog()
        if self._conn is not None:
            try:
                self._conn.close()
            except psycopg.Error:
                pass
            self._conn = None
        self._stop_tunnel()

    def _stop_tunnel(self) -> None:
        if self._tunnel is not None:
            try:
                self._tunnel.stop()
            except Exception:
                pass
            self._tunnel = None

    def _run(
        self,
        sql: str,
        params: tuple = (),
        expect_rowcount: int | None = None,
        fetch_limit: int | None = None,
    ) -> tuple[list[str], list[tuple], int]:
        """Execute one statement; returns (columns, rows, rowcount).

        With expect_rowcount set, the statement runs in its own
        transaction (unless the user already opened one) so a mismatch
        rolls back before the change is durable.
        """
        if self._conn is None:
            raise ConnectorError("Not connected")
        try:
            with self._lock:
                own_tx = expect_rowcount is not None and not self._in_tx()
                if own_tx:
                    self._conn.execute("BEGIN")
                try:
                    with self._conn.cursor() as cur:
                        cur.execute(sql, params or None)
                        if cur.description is not None:
                            columns = [d.name for d in cur.description]
                            rows = list(
                                cur.fetchmany(fetch_limit)
                                if fetch_limit is not None
                                else cur.fetchall()
                            )
                        else:
                            columns, rows = [], []
                        if (
                            expect_rowcount is not None
                            and cur.rowcount != expect_rowcount
                        ):
                            self._conn.execute("ROLLBACK")
                            raise ConnectorError(
                                f"Expected to modify {expect_rowcount} "
                                f"row(s), matched {cur.rowcount}; rolled back"
                            )
                        rowcount = cur.rowcount
                except psycopg.Error:
                    if own_tx and self._in_tx():
                        self._conn.execute("ROLLBACK")
                    raise
                if own_tx and self._in_tx():
                    self._conn.execute("COMMIT")
                return columns, rows, rowcount
        except psycopg.Error as exc:
            raise ConnectorError(_message(exc)) from exc

    def _run_many(self, sql: str, rows: list) -> int:
        """One statement over many rows in a single executemany — what
        a CSV import (CORE-37) sends per batch. It runs no transaction
        control of its own: the caller opened one around the whole
        load, so a failure here unwinds every batch, not just this one.
        """
        if self._conn is None:
            raise ConnectorError("Not connected")
        try:
            with self._lock:
                with self._conn.cursor() as cur:
                    cur.executemany(sql, [tuple(r) for r in rows])
                    return cur.rowcount
        except psycopg.Error as exc:
            raise ConnectorError(_message(exc)) from exc

    def _in_tx(self) -> bool:
        # INTRANS: an explicit BEGIN block is open. INERROR: a block is
        # open but a statement in it failed (still needs ROLLBACK).
        return self._conn.info.transaction_status in (
            TransactionStatus.INTRANS,
            TransactionStatus.INERROR,
        )

    def in_transaction(self) -> bool:
        return self._conn is not None and self._in_tx()

    def rollback(self) -> None:
        if self._conn is None:
            return
        try:
            with self._lock:
                self._conn.execute("ROLLBACK")
        except psycopg.Error as exc:
            raise ConnectorError(_message(exc)) from exc

    def list_databases(self, *, include_system: bool = False) -> list[str]:
        # Every connectable database, system or not: PostgreSQL keeps
        # its catalogs in schemas rather than in databases of their own,
        # so `include_system` has nothing here to add (PG-03).
        _, rows, _ = self._run(
            "SELECT datname FROM pg_database "
            "WHERE datistemplate = false AND datallowconn "
            "ORDER BY datname"
        )
        return [name for (name,) in rows]

    # Accounts and privileges

    supports_users = True

    def list_users(self) -> list[UserInfo]:
        """Every role on the cluster, login roles and group roles
        alike — in PostgreSQL a "user" is only a role that may log in,
        and the groups it belongs to are half of what it can do. The
        pg_* built-in roles stay out; they are the server's, not the
        administrator's.
        """
        _, rows, _ = self._run(
            "SELECT rolname, rolcanlogin, rolsuper, rolcreatedb, "
            "rolcreaterole, rolreplication, rolvaliduntil, rolconnlimit "
            "FROM pg_roles "
            "WHERE rolname NOT LIKE 'pg\\_%' ORDER BY rolname"
        )
        memberships = self._role_memberships()
        users = []
        for (
            name, login, super_, createdb, createrole, replication,
            valid_until, connlimit,
        ) in rows:
            flags = [
                label
                for flag, label in (
                    (super_, "superuser"),
                    (createdb, "createdb"),
                    (createrole, "createrole"),
                    (replication, "replication"),
                    (not login, "no login"),
                )
                if flag
            ]
            users.append(
                UserInfo(
                    name=name,
                    detail=", ".join(flags),
                    can_login=bool(login),
                    # A role that cannot log in is what PostgreSQL
                    # calls a group: the only difference between the
                    # two is the LOGIN attribute.
                    kind="user" if login else "group",
                    superuser=bool(super_),
                    create_db=bool(createdb),
                    create_role=bool(createrole),
                    member_of=tuple(memberships.get(name, ())),
                    valid_until=(
                        "" if valid_until is None else str(valid_until)[:19]
                    ),
                    connection_limit=(
                        "" if connlimit is None else str(connlimit)
                    ),
                )
            )
        return users

    def _role_memberships(self) -> dict[str, list[str]]:
        """Which roles each role is a member of. Its own query rather
        than a join on the listing: a cluster that will not let this
        connection read pg_auth_members should still get its account
        list, one column short."""
        try:
            _, rows, _ = self._run(
                "SELECT m.rolname, g.rolname FROM pg_auth_members am "
                "JOIN pg_roles m ON m.oid = am.member "
                "JOIN pg_roles g ON g.oid = am.roleid "
                "WHERE g.rolname NOT LIKE 'pg\\_%' "
                "ORDER BY m.rolname, g.rolname"
            )
        except ConnectorError:
            return {}
        memberships: dict[str, list[str]] = {}
        for member, group in rows:
            memberships.setdefault(member, []).append(group)
        return memberships

    def list_privileges(self, user: UserInfo) -> list[PrivilegeInfo]:
        """Role attributes, memberships, and the ACL entries granted to
        this role on databases, schemas and tables.

        Databases are cluster-wide, but schemas and tables can only be
        read from the database this connection is attached to: their
        catalogs live inside it. Privileges elsewhere show up when the
        sidebar's other database is opened, which is its own connection.
        """
        privileges = []
        _, rows, _ = self._run(
            "SELECT rolsuper, rolcreatedb, rolcreaterole, rolreplication, "
            "rolcanlogin, rolbypassrls FROM pg_roles WHERE rolname = %s",
            (user.name,),
        )
        if rows:
            for flag, label in zip(
                rows[0],
                (
                    "SUPERUSER", "CREATEDB", "CREATEROLE",
                    "REPLICATION", "LOGIN", "BYPASSRLS",
                ),
            ):
                if flag:
                    privileges.append(PrivilegeInfo("server", label))
        _, rows, _ = self._run(
            "SELECT g.rolname FROM pg_auth_members m "
            "JOIN pg_roles g ON g.oid = m.roleid "
            "JOIN pg_roles r ON r.oid = m.member "
            "WHERE r.rolname = %s ORDER BY g.rolname",
            (user.name,),
        )
        privileges += [
            PrivilegeInfo("role membership", f"member of {name}")
            for (name,) in rows
        ]
        for sql, scope in (
            (
                "SELECT a.privilege_type, a.is_grantable, d.datname "
                "FROM pg_database d, aclexplode(d.datacl) a "
                "JOIN pg_roles r ON r.oid = a.grantee "
                "WHERE r.rolname = %s ORDER BY d.datname, a.privilege_type",
                lambda row: f"database {row[2]}",
            ),
            (
                "SELECT a.privilege_type, a.is_grantable, n.nspname "
                "FROM pg_namespace n, aclexplode(n.nspacl) a "
                "JOIN pg_roles r ON r.oid = a.grantee "
                "WHERE r.rolname = %s ORDER BY n.nspname, a.privilege_type",
                lambda row: f"schema {row[2]}",
            ),
            (
                "SELECT privilege_type, is_grantable, table_schema, table_name "
                "FROM information_schema.table_privileges "
                "WHERE grantee = %s "
                "ORDER BY table_schema, table_name, privilege_type",
                lambda row: f"table {row[2]}.{row[3]}",
            ),
            (
                "SELECT privilege_type, is_grantable, routine_schema, "
                "routine_name FROM information_schema.routine_privileges "
                "WHERE grantee = %s "
                "ORDER BY routine_schema, routine_name, privilege_type",
                lambda row: f"function {row[2]}.{row[3]}",
            ),
        ):
            _, rows, _ = self._run(sql, (user.name,))
            privileges += [
                PrivilegeInfo(
                    scope=scope(row),
                    privilege=row[0],
                    grantable=row[1] in (True, "YES"),
                )
                for row in rows
            ]
        return privileges

    def list_object_grants(self, kind: str, name: str) -> list[PrivilegeInfo]:
        """The ACL entries recorded on one table or view, in the
        schemas on the search path. Other kinds carry no ACL of their
        own — an index belongs to its table, a trigger to the table it
        fires on."""
        if kind not in ("table", "view"):
            return []
        _, rows, _ = self._run(
            "SELECT grantee, privilege_type, is_grantable, grantor "
            "FROM information_schema.table_privileges "
            "WHERE table_name = %s "
            f"AND table_schema IN ({_USER_SCHEMAS}) "
            "ORDER BY grantee, privilege_type",
            (name,),
        )
        return [
            PrivilegeInfo(
                scope=f"role {grantee}",
                privilege=privilege,
                grantable=grantable in (True, "YES"),
                grantor=grantor or "",
            )
            for grantee, privilege, grantable, grantor in rows
        ]

    def list_tables_in(self, schema: str) -> list[TableInfo]:
        """One named schema's tables and views — the search path does
        not come into it, so a schema node shows what it holds even
        when the same name exists nearer the front of the path."""
        _, rows, _ = self._run(
            "SELECT c.relname, c.relkind, c.relispartition "
            "FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f') "
            "AND n.nspname = %s "
            "ORDER BY c.relname",
            (schema,),
        )
        return [
            TableInfo(
                name=name,
                kind="view" if relkind in ("v", "m") else "table",
                detail=_relation_detail(relkind, is_partition),
            )
            for name, relkind, is_partition in rows
        ]

    def grant_scopes(self) -> list[GrantScope]:
        scopes = [
            GrantScope(f"Database: {name}", f"DATABASE {self.quote_ident(name)}")
            for name in self.list_databases()
        ]
        for schema in self.list_schemas():
            quoted = self.quote_ident(schema)
            scopes.append(GrantScope(f"Schema: {schema}", f"SCHEMA {quoted}"))
            scopes.append(
                GrantScope(
                    f"All tables in schema: {schema}",
                    f"ALL TABLES IN SCHEMA {quoted}",
                )
            )
        return scopes

    def privilege_names(self) -> tuple[str, ...]:
        return (
            "ALL PRIVILEGES", "SELECT", "INSERT", "UPDATE", "DELETE",
            "TRUNCATE", "REFERENCES", "TRIGGER", "CREATE", "CONNECT",
            "TEMPORARY", "EXECUTE", "USAGE",
        )

    def create_user_sql(
        self, name: str, host: str = "", password: str = ""
    ) -> str:
        # `host` has no counterpart here: PostgreSQL decides where a
        # role may connect from in pg_hba.conf, not in the role itself.
        sql = f"CREATE ROLE {self.quote_ident(name)} LOGIN"
        if password:
            sql += f" PASSWORD {_quote_str(password)}"
        return sql

    def drop_user_sql(self, user: UserInfo) -> str:
        return f"DROP ROLE {self.quote_ident(user.name)}"

    def set_password_sql(self, user: UserInfo, password: str) -> str:
        return (
            f"ALTER ROLE {self.quote_ident(user.name)} "
            f"PASSWORD {_quote_str(password)}"
        )

    def list_schemas(self, *, include_system: bool = False) -> list[str]:
        """Every schema in the database the user could work in, system
        and temp catalogs excluded — the schema dropdown's list.

        `include_system` keeps `pg_catalog`, `information_schema` and
        the other `pg_*` schemas in, for the object tree that shows
        them dimmed (PG-03). The per-session and per-table catalogs
        (`pg_temp_*`, `pg_toast*`) stay out either way: they are
        bookkeeping, not places anything is browsed.
        """
        where = (
            "nspname NOT LIKE 'pg\\_toast%' "
            "AND nspname NOT LIKE 'pg\\_temp%'"
        )
        if not include_system:
            where = (
                "nspname NOT IN ('pg_catalog', 'information_schema') "
                f"AND {where}"
            )
        _, rows, _ = self._run(
            f"SELECT nspname FROM pg_namespace WHERE {where} ORDER BY nspname"
        )
        return [name for (name,) in rows]

    def current_schema(self) -> str:
        """The schema unqualified names resolve to right now: the
        profile's pick, or whatever the server's search_path starts
        with when the profile left it open."""
        if self.schema:
            return self.schema
        _, rows, _ = self._run("SELECT current_schema()")
        return (rows[0][0] or "") if rows else ""

    def search_path(self) -> str:
        """The effective search path, as the server resolves it right
        now: `current_schemas(true)` rather than the raw `search_path`
        setting, so `"$user"` is already expanded to the schema it
        actually found (or dropped, where there is none) and the
        implicit pg_catalog is shown for what it is.

        The console prints this next to its schema picker: "the schema
        an unqualified name lands in" is not a guess anyone should have
        to make (PG-01).
        """
        _, rows, _ = self._run(
            "SELECT array_to_string(current_schemas(true), ', ')"
        )
        return (rows[0][0] or "") if rows else ""

    def set_search_path(self, schema: str) -> None:
        """Put `schema` at the front of the search path for the rest of
        this session, so unqualified names — in the console, in the
        catalog queries here, in generated DDL — resolve there.

        An empty `schema` restores the server's default rather than
        setting an empty path, which would leave the session unable to
        resolve any bare name at all.
        """
        if not schema:
            self.execute("SET search_path TO DEFAULT")
            self.schema = ""
            # Names now resolve somewhere else, so nothing read under
            # the old path may be reused (CORE-41).
            self.invalidate_catalog()
            return
        _, rows, _ = self._run(
            "SELECT 1 FROM pg_namespace WHERE nspname = %s", (schema,)
        )
        if not rows:
            raise ConnectorError(
                f"No schema named {schema!r} in database {self.database!r}"
            )
        self.execute(f"SET search_path TO {self.quote_ident(schema)}")
        self.schema = schema
        self.invalidate_catalog()

    def list_references(self, table: str) -> list[RelationInfo]:
        """Foreign keys pointing *at* `table`, from anywhere in the
        database.

        Not the inherited implementation, which filters list_relations()
        and so only ever sees the schemas on the search path: a table is
        just as depended-on by a schema nobody put on the path, and
        "nothing references this table" would be a wrong answer rather
        than an empty one (PG-01).
        """
        _, rows, _ = self._run(
            "SELECT sn.nspname, s.relname, sa.attname, "
            "tn.nspname, t.relname, ta.attname "
            "FROM pg_constraint c "
            "JOIN pg_class t ON t.oid = c.confrelid "
            "JOIN pg_namespace tn ON tn.oid = t.relnamespace "
            "JOIN pg_class s ON s.oid = c.conrelid "
            "JOIN pg_namespace sn ON sn.oid = s.relnamespace "
            "JOIN unnest(c.conkey, c.confkey) AS k(src, ref) ON true "
            "JOIN pg_attribute sa "
            "ON sa.attrelid = c.conrelid AND sa.attnum = k.src "
            "JOIN pg_attribute ta "
            "ON ta.attrelid = c.confrelid AND ta.attnum = k.ref "
            "WHERE c.contype = 'f' AND c.confrelid = to_regclass(%s) "
            "ORDER BY sn.nspname, s.relname, sa.attname",
            (self._relation_ref(table),),
        )
        return [
            RelationInfo(
                table=name, column=column,
                ref_table=ref_name, ref_column=ref_column or "",
                schema=schema or "", ref_schema=ref_schema or "",
            )
            for schema, name, column, ref_schema, ref_name, ref_column in rows
        ]

    def list_tables(self) -> list[TableInfo]:
        # relkind: r ordinary table, p partitioned table, v view,
        # m materialized view, f foreign table.
        #
        # DISTINCT ON: with several schemas on the search_path the same
        # relname can appear more than once, and only the earliest is
        # the one a bare `SELECT * FROM orders` would read. Listing all
        # of them would put rows in the tree that resolve to a single
        # table.
        _, rows, _ = self._run(
            "SELECT DISTINCT ON (c.relname) c.relname, c.relkind, "
            "c.relispartition "
            "FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f') "
            f"AND n.nspname IN ({_USER_SCHEMAS}) "
            f"ORDER BY c.relname, {_SEARCH_PATH_RANK}"
        )
        return [
            TableInfo(
                name=name,
                kind="view" if relkind in ("v", "m") else "table",
                detail=_relation_detail(relkind, is_partition),
            )
            for name, relkind, is_partition in rows
        ]

    def list_columns(self, table: str) -> list[ColumnInfo]:
        # attrelid = to_regclass(…), not relname = …: matching on the
        # bare name would pull in a same-named table from every other
        # schema on the search_path and hand back their columns merged
        # into one table that does not exist.
        _, rows, _ = self._run(
            "SELECT a.attname, format_type(a.atttypid, a.atttypmod), "
            "a.attnotnull, "
            "COALESCE(bool_or(ct.contype = 'p'), false) AS is_pk "
            "FROM pg_attribute a "
            "LEFT JOIN pg_constraint ct ON ct.conrelid = a.attrelid "
            "AND ct.contype = 'p' AND a.attnum = ANY(ct.conkey) "
            "WHERE a.attrelid = to_regclass(%s) "
            "AND a.attnum > 0 AND NOT a.attisdropped "
            "GROUP BY a.attname, a.atttypid, a.atttypmod, a.attnotnull, "
            "a.attnum "
            "ORDER BY a.attnum",
            (self._relation_ref(table),),
        )
        return [
            ColumnInfo(
                name=name,
                type=ctype or "",
                is_pk=is_pk,
                nullable=not notnull,
            )
            for name, ctype, notnull, is_pk in rows
        ]

    def list_functions(self) -> list[FunctionInfo]:
        """Functions and procedures (any language, PL/pgSQL included)
        plus triggers — everything the definition tab can edit."""
        _, rows, _ = self._run(
            "SELECT p.proname AS name "
            "FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace "
            f"WHERE n.nspname IN ({_USER_SCHEMAS}) "
            # Aggregates have no body to edit and a folder of their
            # own in the tree (PG-02).
            "AND p.oid NOT IN (SELECT aggfnoid FROM pg_aggregate) "
            "UNION "
            "SELECT t.tgname AS name FROM pg_trigger t "
            "JOIN pg_class c ON c.oid = t.tgrelid "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            f"WHERE NOT t.tgisinternal AND n.nspname IN ({_USER_SCHEMAS}) "
            "ORDER BY name"
        )
        return [FunctionInfo(name=name) for (name,) in rows]

    def list_relations(self) -> list[RelationInfo]:
        """Every foreign key on the search path, both ends named with
        the schema they live in (PG-01).

        A key may point out of its own schema — `sales.orders` into
        `crm.customers` — and a row that says only "customers" is a row
        that cannot be followed: there may be a `customers` in three
        schemas. The schemas travel with the relation and the view
        qualifies the ones that cross (RelationInfo.target).
        """
        _, rows, _ = self._run(
            "SELECT tc.table_schema, tc.table_name, kcu.column_name, "
            "ccu.table_schema AS ref_schema, "
            "ccu.table_name AS ref_table, ccu.column_name AS ref_column "
            "FROM information_schema.table_constraints tc "
            "JOIN information_schema.key_column_usage kcu "
            "ON kcu.constraint_name = tc.constraint_name "
            "AND kcu.constraint_schema = tc.constraint_schema "
            "JOIN information_schema.constraint_column_usage ccu "
            "ON ccu.constraint_name = tc.constraint_name "
            "AND ccu.constraint_schema = tc.constraint_schema "
            "WHERE tc.constraint_type = 'FOREIGN KEY' "
            f"AND tc.table_schema IN ({_USER_SCHEMAS}) "
            "ORDER BY tc.table_schema, tc.table_name, kcu.column_name"
        )
        return [
            RelationInfo(
                table=table, column=column,
                ref_table=ref_table, ref_column=ref_column or "",
                schema=schema or "", ref_schema=ref_schema or "",
            )
            for schema, table, column, ref_schema, ref_table, ref_column
            in rows
        ]

    # Table properties (CORE-04). Every lookup goes through
    # to_regclass(), which resolves a quoted name against the search
    # path and answers NULL instead of raising for a name that is not
    # a relation — so an object that vanished between two clicks costs
    # an empty section, not an error.

    #: pg_constraint.contype -> the word the properties view shows.
    _CONSTRAINT_KINDS = {
        "p": "PRIMARY KEY",
        "u": "UNIQUE",
        "f": "FOREIGN KEY",
        "c": "CHECK",
        "x": "EXCLUDE",
        "t": "TRIGGER",
    }

    def table_stats(self, table: str) -> TableStats:
        _, rows, _ = self._run(
            "SELECT c.relkind, pg_get_userbyid(c.relowner), "
            "pg_size_pretty(pg_total_relation_size(c.oid)), "
            "c.reltuples::bigint, obj_description(c.oid, 'pg_class') "
            "FROM pg_class c WHERE c.oid = to_regclass(%s)",
            (self._relation_ref(table),),
        )
        if not rows:
            return TableStats()
        relkind, owner, size, estimate, comment = rows[0]
        kinds = {
            "r": "table", "p": "partitioned table", "v": "view",
            "m": "materialized view", "f": "foreign table",
        }
        return TableStats(
            kind=kinds.get(relkind, ""),
            owner=owner or "",
            size=size or "",
            # -1 is "never analysed", which is not an estimate.
            rows="" if estimate is None or estimate < 0 else str(estimate),
            comment=comment or "",
        )

    def list_constraints(self, table: str) -> list[ConstraintInfo]:
        _, rows, _ = self._run(
            "SELECT con.conname, con.contype, "
            "pg_get_constraintdef(con.oid), "
            "(SELECT string_agg(a.attname, ', ' ORDER BY a.attnum) "
            " FROM pg_attribute a "
            " WHERE a.attrelid = con.conrelid "
            " AND a.attnum = ANY (con.conkey)) "
            "FROM pg_constraint con "
            "WHERE con.conrelid = to_regclass(%s) "
            "ORDER BY con.contype, con.conname",
            (self._relation_ref(table),),
        )
        return [
            ConstraintInfo(
                name=name,
                kind=self._CONSTRAINT_KINDS.get(contype, contype or ""),
                table=table,
                columns=columns or "",
                definition=definition or "",
            )
            for name, contype, definition, columns in rows
        ]

    def list_partitions(self, table: str) -> list[ObjectSummary]:
        _, rows, _ = self._run(
            "SELECT c.relname, pg_get_expr(c.relpartbound, c.oid), "
            "pg_size_pretty(pg_total_relation_size(c.oid)) "
            "FROM pg_inherits i JOIN pg_class c ON c.oid = i.inhrelid "
            "WHERE i.inhparent = to_regclass(%s) ORDER BY c.relname",
            (self._relation_ref(table),),
        )
        return [
            ObjectSummary(
                name=name, kind="table", detail=size or "",
                definition=bound or "",
            )
            for name, bound, size in rows
        ]

    def list_rules(self, table: str) -> list[ObjectSummary]:
        _, rows, _ = self._run(
            "SELECT r.rulename, pg_get_ruledef(r.oid) FROM pg_rewrite r "
            "WHERE r.ev_class = to_regclass(%s) AND r.rulename <> '_RETURN' "
            "ORDER BY r.rulename",
            (self._relation_ref(table),),
        )
        return [
            ObjectSummary(name=name, definition=(definition or "").strip())
            for name, definition in rows
        ]

    def list_policies(self, table: str) -> list[ObjectSummary]:
        _, rows, _ = self._run(
            "SELECT p.polname, p.polcmd, "
            "pg_get_expr(p.polqual, p.polrelid) "
            "FROM pg_policy p WHERE p.polrelid = to_regclass(%s) "
            "ORDER BY p.polname",
            (self._relation_ref(table),),
        )
        commands = {
            "r": "SELECT", "a": "INSERT", "w": "UPDATE", "d": "DELETE",
            "*": "ALL",
        }
        return [
            ObjectSummary(
                name=name,
                detail=commands.get(command, command or ""),
                definition=using or "",
            )
            for name, command, using in rows
        ]

    def list_dependencies(self, table: str) -> list[ObjectSummary]:
        """Views and materialized views built on this table — what a
        DROP would take with it, or refuse over."""
        _, rows, _ = self._run(
            "SELECT DISTINCT dependent.relname, dependent.relkind "
            "FROM pg_depend d "
            "JOIN pg_rewrite r ON r.oid = d.objid "
            "JOIN pg_class dependent ON dependent.oid = r.ev_class "
            "WHERE d.refobjid = to_regclass(%s) "
            "AND dependent.oid <> to_regclass(%s) "
            "ORDER BY dependent.relname",
            (self._relation_ref(table), self._relation_ref(table)),
        )
        kinds = {"v": "view", "m": "materialized view", "r": "table"}
        return [
            ObjectSummary(
                name=name,
                kind="view" if relkind in ("v", "m") else "table",
                detail=kinds.get(relkind, ""),
            )
            for name, relkind in rows
        ]

    def list_table_functions(self, table: str) -> list[ObjectSummary]:
        """The functions this table's triggers call."""
        _, rows, _ = self._run(
            "SELECT p.proname, t.tgname FROM pg_trigger t "
            "JOIN pg_proc p ON p.oid = t.tgfoid "
            "WHERE t.tgrelid = to_regclass(%s) AND NOT t.tgisinternal "
            "ORDER BY p.proname",
            (self._relation_ref(table),),
        )
        return [
            ObjectSummary(
                name=name, kind="function", detail=f"called by {trigger}",
            )
            for name, trigger in rows
        ]

    # The catalog folders the object tree grows beyond tables and
    # views (PG-02). One method, one slug per folder — see
    # Connector.list_catalog for why they are not a method each.

    def list_catalog(self, slug: str, schema: str = "") -> list[ObjectSummary]:
        reader = {
            "sequences": self._catalog_sequences,
            "data_types": self._catalog_data_types,
            "aggregates": self._catalog_aggregates,
            "extensions": self._catalog_extensions,
            "available_extensions": self._catalog_available_extensions,
            "event_triggers": self._catalog_event_triggers,
            "storage": self._catalog_storage,
            "system_info": self._catalog_system_info,
        }.get(slug)
        if reader is None:
            return []
        return reader(schema or self.current_schema())

    def _catalog_sequences(self, schema: str) -> list[ObjectSummary]:
        # pg_class rather than pg_sequences: the view is only readable
        # for sequences the account may select from, and a sequence it
        # may not read is still a sequence that is there.
        _, rows, _ = self._run(
            "SELECT c.relname, pg_get_userbyid(c.relowner) "
            "FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE c.relkind = 'S' AND n.nspname = %s ORDER BY c.relname",
            (schema,),
        )
        return [
            ObjectSummary(name=name, kind="sequence", detail=f"owner {owner}")
            for name, owner in rows
        ]

    def _catalog_data_types(self, schema: str) -> list[ObjectSummary]:
        # Only types someone declared: the row type every table gets
        # for free, and the array type every type gets for free, are
        # the catalog's business and not a node in anybody's tree.
        _, rows, _ = self._run(
            "SELECT t.typname, t.typtype, format_type(t.oid, NULL) "
            "FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace "
            "LEFT JOIN pg_class c ON c.oid = t.typrelid "
            "WHERE n.nspname = %s "
            "AND t.typtype IN ('b', 'c', 'd', 'e', 'r') "
            "AND (c.oid IS NULL OR c.relkind = 'c') "
            "AND NOT EXISTS ("
            " SELECT 1 FROM pg_type e"
            " WHERE e.oid = t.typelem AND e.typarray = t.oid) "
            "ORDER BY t.typname",
            (schema,),
        )
        kinds = {
            "b": "base", "c": "composite", "d": "domain",
            "e": "enum", "r": "range",
        }
        return [
            ObjectSummary(
                name=name,
                kind="data_type",
                detail=kinds.get(typtype, ""),
                definition=printed or "",
            )
            for name, typtype, printed in rows
        ]

    def _catalog_aggregates(self, schema: str) -> list[ObjectSummary]:
        # pg_aggregate rather than prokind = 'a': PostgreSQL 10 has no
        # prokind column, and the membership test reads the same on
        # every supported version.
        _, rows, _ = self._run(
            "SELECT p.proname, pg_get_function_identity_arguments(p.oid), "
            "format_type(p.prorettype, NULL) "
            "FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace "
            "WHERE n.nspname = %s "
            "AND p.oid IN (SELECT aggfnoid FROM pg_aggregate) "
            "ORDER BY p.proname",
            (schema,),
        )
        return [
            ObjectSummary(
                name=name,
                kind="aggregate",
                detail=f"({args}) → {returns}" if args else f"→ {returns}",
            )
            for name, args, returns in rows
        ]

    def list_extensions(self) -> list[ExtensionState]:
        """Every extension this server has, installed or not (PG-05).

        pg_available_extensions is the outer side: it holds one row per
        extension the server has files for, with the version it would
        install and the comment it ships with, and `installed_version`
        for the ones already in this database. pg_extension is joined
        for the schema, which only an installed extension has.

        A server that refuses the view (or is too old for a column of
        it) raises like any other catalog query; the callers wrap this
        in `_safe` and show an empty folder rather than an error.
        """
        _, rows, _ = self._run(
            "SELECT a.name, COALESCE(a.installed_version, ''), "
            "COALESCE(n.nspname, ''), COALESCE(a.default_version, ''), "
            "COALESCE(a.comment, '') "
            "FROM pg_available_extensions a "
            "LEFT JOIN pg_extension e ON e.extname = a.name "
            "LEFT JOIN pg_namespace n ON n.oid = e.extnamespace "
            "ORDER BY a.name"
        )
        return [
            ExtensionState(
                name=name,
                version=version,
                schema=schema,
                default_version=default_version,
                comment=comment,
            )
            for name, version, schema, default_version, comment in rows
        ]

    def can_manage_extensions(self) -> bool:
        """CREATE EXTENSION is a superuser action on every supported
        version — trusted extensions (PostgreSQL 13+) also need CREATE
        on the target schema, which is more than the catalog can say
        for the schema the user has not chosen yet. Superuser is
        therefore the gate the actions are offered behind; a role that
        is refused anyway gets the server's error, not a silent
        no-op."""
        _, rows, _ = self._run(
            "SELECT rolsuper FROM pg_roles WHERE rolname = current_user"
        )
        return bool(rows and rows[0][0])

    def extension_owner(self, name: str, schema: str = "") -> str:
        """The extension an object belongs to, "" for a user object.

        pg_depend records extension membership as a dependency of type
        'e' from the object to its extension; asked by name across the
        catalogs a tree row can come from (relations, routines, types),
        so one query answers for every kind the info view describes.
        """
        _, rows, _ = self._run(
            "SELECT e.extname FROM pg_depend d "
            "JOIN pg_extension e ON e.oid = d.refobjid "
            "WHERE d.deptype = 'e' AND d.refclassid = 'pg_extension'::regclass "
            "AND ("
            " (d.classid = 'pg_class'::regclass AND d.objid IN ("
            "  SELECT c.oid FROM pg_class c"
            "  JOIN pg_namespace n ON n.oid = c.relnamespace"
            "  WHERE c.relname = %(name)s"
            "  AND (%(schema)s = '' OR n.nspname = %(schema)s)))"
            " OR (d.classid = 'pg_proc'::regclass AND d.objid IN ("
            "  SELECT p.oid FROM pg_proc p"
            "  JOIN pg_namespace n ON n.oid = p.pronamespace"
            "  WHERE p.proname = %(name)s"
            "  AND (%(schema)s = '' OR n.nspname = %(schema)s)))"
            " OR (d.classid = 'pg_type'::regclass AND d.objid IN ("
            "  SELECT t.oid FROM pg_type t"
            "  JOIN pg_namespace n ON n.oid = t.typnamespace"
            "  WHERE t.typname = %(name)s"
            "  AND (%(schema)s = '' OR n.nspname = %(schema)s)))"
            ") LIMIT 1",
            {"name": name, "schema": schema or ""},
        )
        return rows[0][0] if rows else ""

    def _catalog_extensions(self, _schema: str) -> list[ObjectSummary]:
        return [
            ObjectSummary(
                name=state.name,
                kind="extension",
                detail=state.detail(),
                definition=state.comment,
            )
            for state in self.list_extensions()
            if state.installed
        ]

    def _catalog_available_extensions(
        self, _schema: str
    ) -> list[ObjectSummary]:
        """The other half of the same listing: what could be installed
        and is not. Kept a folder of its own so the Extensions folder
        stays "what this database has" (PG-05)."""
        return [
            ObjectSummary(
                name=state.name,
                kind="extension",
                detail=state.detail(),
                definition=state.comment,
            )
            for state in self.list_extensions()
            if not state.installed
        ]

    def _catalog_event_triggers(self, _schema: str) -> list[ObjectSummary]:
        _, rows, _ = self._run(
            "SELECT evtname, evtevent, evtenabled, "
            "pg_get_userbyid(evtowner) "
            "FROM pg_event_trigger ORDER BY evtname"
        )
        return [
            ObjectSummary(
                name=name,
                kind="event_trigger",
                detail=(
                    f"{event}"
                    + ("" if enabled == "O" else " · disabled")
                    + f" · owner {owner}"
                ),
            )
            for name, event, enabled, owner in rows
        ]

    def _catalog_storage(self, _schema: str) -> list[ObjectSummary]:
        # Tablespaces and their owners only: a size per tablespace
        # needs pg_tablespace_size(), which walks the whole directory
        # and is refused outright to an unprivileged account — neither
        # belongs in a folder that opens on expand (PG-02).
        _, rows, _ = self._run(
            "SELECT spcname, pg_get_userbyid(spcowner) "
            "FROM pg_tablespace ORDER BY spcname"
        )
        return [
            ObjectSummary(
                name=name, kind="tablespace", detail=f"owner {owner}"
            )
            for name, owner in rows
        ]

    #: The server settings the System Info folder reports, in the
    #: order it shows them. A curated list rather than all of
    #: pg_settings: three hundred rows is a catalog dump, not a tree.
    _SYSTEM_SETTINGS = (
        "server_version",
        "server_encoding",
        "lc_collate",
        "lc_ctype",
        "TimeZone",
        "max_connections",
        "shared_buffers",
        "work_mem",
        "data_checksums",
        "is_superuser",
    )

    def _catalog_system_info(self, _schema: str) -> list[ObjectSummary]:
        """The server and the connected database, as name/value rows.

        pg_settings is served from memory and the database row reads
        one pg_database tuple, so the folder costs no scan however big
        the cluster is.
        """
        _, rows, _ = self._run(
            "SELECT name, setting, short_desc FROM pg_settings "
            "WHERE name = ANY(%s)",
            (list(self._SYSTEM_SETTINGS),),
        )
        order = {name: i for i, name in enumerate(self._SYSTEM_SETTINGS)}
        found = sorted(rows, key=lambda row: order.get(row[0], len(order)))
        entries = [
            ObjectSummary(
                name=name, kind="setting", detail=value or "",
                definition=description or "",
            )
            for name, value, description in found
        ]
        _, extra, _ = self._run(
            "SELECT current_database(), "
            "pg_encoding_to_char(d.encoding), d.datcollate, "
            "pg_get_userbyid(d.datdba), "
            "pg_size_pretty(pg_database_size(d.datname)) "
            "FROM pg_database d WHERE d.datname = current_database()"
        )
        for name, encoding, collation, owner, size in extra:
            entries += [
                ObjectSummary(
                    name="database", kind="setting", detail=name,
                    definition="The database this connection is attached to",
                ),
                ObjectSummary(
                    name="database_encoding", kind="setting",
                    detail=encoding or "",
                ),
                ObjectSummary(
                    name="database_collation", kind="setting",
                    detail=collation or "",
                ),
                ObjectSummary(
                    name="database_owner", kind="setting", detail=owner or "",
                ),
                ObjectSummary(
                    name="database_size", kind="setting", detail=size or "",
                ),
            ]
        return entries

    def _relation_ref(self, name: str) -> str:
        """`name` as text to_regclass() can resolve.

        Quoted, so a name that is a keyword, has capitals or contains a
        dot stays one identifier instead of being read as
        schema.table — and so no name can steer the lookup somewhere
        the caller did not mean.
        """
        return self.quote_ident(name)

    def get_ddl(self, name: str) -> str:
        """CREATE statement for a table, view, function/procedure or
        trigger named `name` (the sidebar preview and definition tab)."""
        # Relations first: to_regclass resolves against the search_path
        # and returns NULL rather than erroring on a non-relation name.
        _, rows, _ = self._run(
            "SELECT c.relkind, c.oid FROM pg_class c "
            "WHERE c.oid = to_regclass(%s)",
            (self._relation_ref(name),),
        )
        if rows:
            relkind, oid = rows[0]
            if relkind in ("v", "m"):
                _, vrows, _ = self._run(
                    "SELECT pg_get_viewdef(%s, true)", (oid,)
                )
                body = (vrows[0][0] or "").rstrip() if vrows else ""
                verb = "MATERIALIZED VIEW" if relkind == "m" else "VIEW"
                return (
                    f"CREATE {verb} {self.quote_ident(name)} AS\n{body}"
                    if body else ""
                )
            return self._table_ddl(name)

        # Function or procedure (pg_get_functiondef emits CREATE OR
        # REPLACE ... with the full body, language and all).
        _, frows, _ = self._run(
            "SELECT pg_get_functiondef(p.oid) "
            "FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace "
            f"WHERE p.proname = %s AND n.nspname IN ({_USER_SCHEMAS}) "
            "LIMIT 1",
            (name,),
        )
        if frows and frows[0][0]:
            return frows[0][0]

        # Trigger.
        _, trows, _ = self._run(
            "SELECT pg_get_triggerdef(oid, true) FROM pg_trigger "
            "WHERE tgname = %s AND NOT tgisinternal LIMIT 1",
            (name,),
        )
        if trows and trows[0][0]:
            return trows[0][0]
        return ""

    def _table_ddl(self, table: str, foreign_keys: bool = True) -> str:
        """Synthesize a CREATE TABLE from the catalog (Postgres has no
        pg_get_tabledef): columns with types, identity/defaults, NOT
        NULL, and the table's constraints.

        `foreign_keys=False` omits them, for schema_ddl's separate
        pass."""
        # attidentity: '' plain, 'a' GENERATED ALWAYS, 'd' GENERATED BY
        # DEFAULT. An identity column has no pg_attrdef row, so without
        # this it would come back as a bare integer and the rebuilt
        # table would have lost its generator.
        _, rows, _ = self._run(
            "SELECT a.attname, format_type(a.atttypid, a.atttypmod), "
            "a.attnotnull, pg_get_expr(ad.adbin, ad.adrelid) AS default, "
            "a.attidentity "
            "FROM pg_attribute a "
            "LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid "
            "AND ad.adnum = a.attnum "
            "WHERE a.attrelid = to_regclass(%s) "
            "AND a.attnum > 0 AND NOT a.attisdropped "
            "ORDER BY a.attnum",
            (self._relation_ref(table),),
        )
        if not rows:
            return ""
        defs = []
        for attname, ctype, notnull, default, identity in rows:
            line = f"  {self.quote_ident(attname)} {ctype}"
            if identity in ("a", "d"):
                always = "ALWAYS" if identity == "a" else "BY DEFAULT"
                line += f" GENERATED {always} AS IDENTITY"
            elif default is not None:
                line += f" DEFAULT {default}"
            if notnull:
                line += " NOT NULL"
            defs.append(line)
        defs.extend(
            f"  {c}" for _n, c in self._table_constraints(table, foreign_keys)
        )
        return (
            f"CREATE TABLE {self.quote_ident(table)} (\n"
            + ",\n".join(defs)
            + "\n)"
        )

    def _table_constraints(
        self, table: str, foreign_keys: bool = True
    ) -> list[tuple[str, str]]:
        """The table's constraints as (name, definition) pairs, spelled
        the way PostgreSQL spells them.

        pg_get_constraintdef rather than a hand-built PRIMARY KEY line:
        a table's shape is also its foreign keys, its UNIQUE and its
        CHECK constraints, and DDL that quietly drops them is DDL that
        rebuilds a different table.

        `foreign_keys=False` leaves the foreign keys out, for a caller
        that will add them separately (see schema_ddl).
        """
        # p primary key, u unique, f foreign key, c check. Others
        # (trigger constraints) are not part of a CREATE TABLE.
        kinds = "'p', 'u', 'f', 'c'" if foreign_keys else "'p', 'u', 'c'"
        _, rows, _ = self._run(
            "SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint "
            "WHERE conrelid = to_regclass(%s) "
            f"AND contype IN ({kinds}) "
            "ORDER BY contype, conname",
            (self._relation_ref(table),),
        )
        return [(name, defn) for name, defn in rows if defn]

    def _foreign_key_statements(self, tables: list[str]) -> list[str]:
        """Every table's foreign keys as standalone ALTER TABLE …
        ADD CONSTRAINT, for the end of a schema script."""
        statements = []
        for table in tables:
            for name, definition in self._foreign_keys(table):
                statements.append(
                    f"ALTER TABLE {self.quote_ident(table)} "
                    f"ADD CONSTRAINT {self.quote_ident(name)} {definition}"
                )
        return statements

    def _foreign_keys(self, table: str) -> list[tuple[str, str]]:
        _, rows, _ = self._run(
            "SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint "
            "WHERE conrelid = to_regclass(%s) AND contype = 'f' "
            "ORDER BY conname",
            (self._relation_ref(table),),
        )
        return [(name, defn) for name, defn in rows if defn]

    def schema_ddl(self) -> list[str]:
        """Tables, their foreign keys, their indexes, then views and
        programmable objects.

        The generic walk is not enough here, for two reasons.

        A PostgreSQL CREATE TABLE carries its constraints but not its
        indexes, which are objects of their own and need their own
        CREATE INDEX (pg_get_indexdef writes it). Constraint-backed
        indexes are left out — their CREATE TABLE already made them,
        and issuing them again would fail.

        And foreign keys come last, as ALTER TABLE … ADD CONSTRAINT,
        rather than inside the CREATE TABLE where get_ddl puts them.
        Tables can only be listed in one order, and any order is the
        wrong one for some pair of tables that reference each other —
        including a table that references itself. Adding the
        references once every table exists is the only ordering that
        always replays.
        """
        objects = self.list_tables()
        tables = [t.name for t in objects if t.kind != "view"]
        statements = [
            ddl
            for t in tables
            if (ddl := self._table_ddl(t, foreign_keys=False).strip())
        ]
        statements.extend(self._foreign_key_statements(tables))
        _, rows, _ = self._run(
            "SELECT pg_get_indexdef(i.indexrelid) FROM pg_index i "
            "JOIN pg_class c ON c.oid = i.indexrelid "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            f"WHERE n.nspname IN ({_USER_SCHEMAS}) "
            "AND NOT EXISTS (SELECT 1 FROM pg_constraint con "
            "WHERE con.conindid = i.indexrelid) "
            "ORDER BY c.relname"
        )
        statements.extend(sql for (sql,) in rows if sql)
        statements.extend(
            self.ddl_for(
                [t.name for t in objects if t.kind == "view"]
                + [f.name for f in self.list_functions()]
            )
        )
        return statements

    def list_indexes(self) -> list[IndexInfo]:
        # Indexes backing PRIMARY KEY/UNIQUE constraints cannot be
        # dropped with DROP INDEX, so they stay out.
        _, rows, _ = self._run(
            "SELECT c.relname, t.relname, pg_get_indexdef(i.indexrelid) "
            "FROM pg_index i "
            "JOIN pg_class c ON c.oid = i.indexrelid "
            "JOIN pg_class t ON t.oid = i.indrelid "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            f"WHERE n.nspname IN ({_USER_SCHEMAS}) "
            "AND NOT EXISTS (SELECT 1 FROM pg_constraint con "
            "WHERE con.conindid = i.indexrelid) "
            "ORDER BY c.relname"
        )
        return [
            IndexInfo(name=name, table=table, ddl=ddl or "")
            for name, table, ddl in rows
        ]

    def list_triggers(self) -> list[TriggerInfo]:
        _, rows, _ = self._run(
            "SELECT t.tgname, c.relname, pg_get_triggerdef(t.oid) "
            "FROM pg_trigger t "
            "JOIN pg_class c ON c.oid = t.tgrelid "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            f"WHERE NOT t.tgisinternal AND n.nspname IN ({_USER_SCHEMAS}) "
            "ORDER BY t.tgname"
        )
        return [
            TriggerInfo(name=name, table=table, ddl=ddl or "")
            for name, table, ddl in rows
        ]

    supports_drop_cascade = True

    def ddl_kinds(self) -> tuple[str, ...]:
        return ("table", "view", "index", "trigger", "function", "procedure")

    def drop_sql(
        self, kind: str, name: str, table: str = "", cascade: bool = False
    ) -> str:
        if kind == "trigger":
            if not table:
                # The sidebar usually passes the owning table; a bare
                # name (Functions category) looks it up.
                _, rows, _ = self._run(
                    "SELECT c.relname FROM pg_trigger t "
                    "JOIN pg_class c ON c.oid = t.tgrelid "
                    "JOIN pg_namespace n ON n.oid = c.relnamespace "
                    "WHERE t.tgname = %s AND NOT t.tgisinternal "
                    f"AND n.nspname IN ({_USER_SCHEMAS}) "
                    f"ORDER BY {_SEARCH_PATH_RANK} LIMIT 1",
                    (name,),
                )
                if not rows:
                    raise ConnectorError(f"No such trigger: {name}")
                table = rows[0][0]
            sql = (
                f"DROP TRIGGER {self.quote_ident(name)} "
                f"ON {self.quote_ident(table)}"
            )
        elif kind in ("function", "procedure"):
            # DROP FUNCTION name is ambiguous with overloads: drop via
            # the full regprocedure signature. The catalog also decides
            # FUNCTION vs PROCEDURE (both live under Functions in the
            # sidebar).
            signature, is_procedure = self._routine_signature(name)
            verb = "PROCEDURE" if is_procedure else "FUNCTION"
            sql = f"DROP {verb} {signature}"
        else:
            sql = super().drop_sql(kind, name, table=table)
        return sql + (" CASCADE" if cascade else "")

    def _routine_signature(self, name: str) -> tuple[str, bool]:
        """(regprocedure signature, is-procedure) for the first
        function/procedure named `name` on the search_path."""
        sql = (
            "SELECT p.oid::regprocedure::text, p.prokind = 'p' "
            "FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace "
            f"WHERE p.proname = %s AND n.nspname IN ({_USER_SCHEMAS}) "
            f"ORDER BY {_SEARCH_PATH_RANK} "
            "LIMIT 1"
        )
        try:
            _, rows, _ = self._run(sql, (name,))
        except ConnectorError:
            # PostgreSQL 10: no prokind column (and no procedures).
            _, rows, _ = self._run(
                sql.replace("p.prokind = 'p'", "false"), (name,)
            )
        if not rows:
            raise ConnectorError(f"No such function or procedure: {name}")
        return rows[0][0], bool(rows[0][1])

    def create_template(self, kind: str) -> str:
        return _TEMPLATES.get(kind, "")

    def column_type_specs(self) -> list[TypeSpec]:
        return [
            TypeSpec("integer"),
            TypeSpec("bigint"),
            TypeSpec("smallint"),
            TypeSpec("serial", note="integer + own sequence"),
            TypeSpec("bigserial", note="bigint + own sequence"),
            TypeSpec("numeric", ("precision", "scale"), ("10", "2")),
            TypeSpec("real"),
            TypeSpec("double precision"),
            TypeSpec("money"),
            TypeSpec("text", note="unlimited; no length needed"),
            TypeSpec("varchar", ("length",), ("255",)),
            TypeSpec("char", ("length",), ("1",), "blank-padded"),
            TypeSpec("boolean"),
            TypeSpec("date"),
            TypeSpec("time", ("precision",)),
            TypeSpec("timestamp", ("precision",), note="without time zone"),
            TypeSpec("timestamptz", ("precision",), note="with time zone"),
            TypeSpec("interval"),
            TypeSpec("uuid"),
            TypeSpec("json"),
            TypeSpec("jsonb", note="binary, indexable"),
            TypeSpec("bytea"),
            TypeSpec("inet"),
            TypeSpec("cidr"),
            TypeSpec("macaddr"),
            TypeSpec("xml"),
        ]

    def drop_function_sql(self, name: str) -> str:
        """DROP for a stored object so an edited CREATE can be re-run.

        Functions and procedures need none — pg_get_functiondef emits
        CREATE OR REPLACE, which replaces in place. Triggers have no
        OR REPLACE before PG 14, so they get an explicit DROP … ON
        table (the table is looked up from the catalog)."""
        _, rows, _ = self._run(
            "SELECT c.relname FROM pg_trigger t "
            "JOIN pg_class c ON c.oid = t.tgrelid "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE t.tgname = %s AND NOT t.tgisinternal "
            f"AND n.nspname IN ({_USER_SCHEMAS}) "
            f"ORDER BY {_SEARCH_PATH_RANK} LIMIT 1",
            (name,),
        )
        if rows:
            table = rows[0][0]
            return (
                f"DROP TRIGGER IF EXISTS {self.quote_ident(name)} "
                f"ON {self.quote_ident(table)}"
            )
        return ""

    # A rename carries the table's identity, so other tables' foreign
    # keys follow the backup rather than staying with the name: the
    # DROP then fails, and would leave the rebuilt table unreferenced
    # if it didn't. ALTER TABLE covers every edit this path was for.
    supports_table_rebuild = False
    identifier_max_length = 63

    def modify_column_sql(self, table: str, column: ColumnInfo) -> str:
        # Postgres splits type and nullability into separate ALTER
        # COLUMN actions; both ride on one ALTER TABLE.
        null_action = (
            "DROP NOT NULL" if column.nullable else "SET NOT NULL"
        )
        return (
            f"ALTER TABLE {self.quote_ident(table)} "
            f"ALTER COLUMN {self.quote_ident(column.name)} "
            f"TYPE {column.type}, "
            f"ALTER COLUMN {self.quote_ident(column.name)} {null_action}"
        )

    def row_key_columns(self, table: str) -> list[str]:
        """The columns of the narrowest usable unique key (CORE-40).

        The primary key first, then any other valid, total, non-partial
        unique index whose columns are all NOT NULL — a table without a
        declared primary key very often has one of those, and it orders
        and pages exactly as well.

        Deliberately not ctid: it is unique at any instant but an UPDATE
        or a VACUUM moves a row to a new one, so a cursor carrying a
        ctid forward would skip rows the moment the table changed under
        the user. A relation with no key of its own pages by offset and
        says the order is not guaranteed instead.
        """
        _, rows, _ = self._run(
            "SELECT i.indexrelid, i.indisprimary, a.attname, k.ord, "
            "array_length(i.indkey::int2[], 1) "
            "FROM pg_index i "
            "JOIN LATERAL generate_subscripts(i.indkey::int2[], 1) AS k(ord) "
            "ON true "
            "JOIN pg_attribute a ON a.attrelid = i.indrelid "
            "AND a.attnum = (i.indkey::int2[])[k.ord] "
            "WHERE i.indrelid = to_regclass(%s) "
            "AND i.indisunique AND i.indisvalid AND i.indpred IS NULL "
            "AND a.attnotnull AND NOT a.attisdropped "
            "ORDER BY i.indisprimary DESC, i.indexrelid, k.ord",
            (self._relation_ref(table),),
        )
        indexes: dict[Any, tuple[int, list[str]]] = {}
        for oid, _primary, name, _ord, width in rows:
            indexes.setdefault(oid, (width, []))[1].append(name)
        for width, names in indexes.values():
            # A short group means the index also covers a nullable or an
            # expression column, which is no key for paging.
            if width == len(names):
                return names
        return []

    def fetch_rows(
        self,
        table: str,
        offset: int = 0,
        limit: int = 500,
        filters: list[FilterCondition] | None = None,
        order_by: list[SortSpec] | None = None,
        cursor: PageCursor | None = None,
    ) -> ResultSet:
        self._assert_known_table(table)
        self._assert_filter_columns(table, filters, order_by)
        query = self._page_query(
            table, offset, limit, filters, order_by, cursor,
            placeholder="%s",
        )
        columns, rows, _ = self._run(query.sql, tuple(query.params))
        return self._page_result(columns, rows, query)

    def run_bound(
        self, sql: str, params=(), max_rows: int | None = None
    ) -> ResultSet:
        limit = max_rows + 1 if max_rows else None
        columns, rows, _ = self._run(sql, tuple(params), fetch_limit=limit)
        return self._bound_result(sql, params, columns, rows, max_rows, "%s")

    def execute(self, sql: str, max_rows: int | None = None) -> ResultSet | int:
        # One row past the cap: the extra is what tells truncated from
        # a result that happens to be exactly max_rows long.
        limit = max_rows + 1 if max_rows else None
        try:
            columns, rows, rowcount = self._run(sql, fetch_limit=limit)
        finally:
            # In a finally: a DDL statement that failed may still have
            # applied part of itself (MySQL commits each one), so the
            # cache is dropped whether or not the statement succeeded.
            self._note_statement(sql)
        if columns:
            truncated = max_rows is not None and len(rows) > max_rows
            return ResultSet(
                columns=columns,
                rows=rows[:max_rows] if truncated else rows,
                truncated=truncated,
            )
        return max(rowcount, 0)

    supports_cancel = True

    def cancel(self) -> None:
        """Send a cancel request over a side channel to the backend
        running our statement.

        Deliberately outside self._lock: the lock is held by the thread
        blocked in execute(), which is exactly the thread we are trying
        to unblock. psycopg's cancel path is documented as safe to call
        from another thread for this reason. cancel_safe() (3.2+) does
        it over the encrypted connection; cancel() is the legacy
        plaintext fallback.
        """
        conn = self._conn
        if conn is None:
            return
        try:
            if hasattr(conn, "cancel_safe"):
                conn.cancel_safe()
            else:
                conn.cancel()
        except psycopg.Error as exc:
            raise ConnectorError(_message(exc)) from exc

    def update_cell(
        self, table: str, pk_values: dict[str, Any], column: str, value: Any
    ) -> None:
        if not pk_values:
            raise ConnectorError(
                "Refusing to update without a primary-key filter"
            )
        # Only identifiers the catalog vouches for reach the SQL text
        # (cached, and re-read on a miss before rejecting anything).
        self._assert_known_columns(table, {column, *pk_values})
        where = " AND ".join(f"{self.quote_ident(k)} = %s" for k in pk_values)
        sql = (
            f"UPDATE {self.quote_ident(table)} "
            f"SET {self.quote_ident(column)} = %s WHERE {where}"
        )
        self._run(sql, (value, *pk_values.values()), expect_rowcount=1)

    def quote_ident(self, name: str) -> str:
        if not name:
            raise ConnectorError("Empty identifier")
        if "\x00" in name:
            raise ConnectorError("Identifier contains a NUL byte")
        return '"' + name.replace('"', '""') + '"'


def _quote_str(value: str) -> str:
    """A string literal for a statement the user is about to review —
    a password inside CREATE ROLE cannot be bound as a parameter.
    Doubling the quote is the whole escape: PostgreSQL has had
    standard_conforming_strings on since 9.1, so a backslash in a
    plain literal is a backslash."""
    if "\x00" in value:
        raise ConnectorError("Value contains a NUL byte")
    return "'" + value.replace("'", "''") + "'"


def _message(exc: psycopg.Error) -> str:
    # psycopg wraps the server's primary message on the diag object;
    # it reads better in a toast than the full exception repr.
    diag = getattr(exc, "diag", None)
    primary = getattr(diag, "message_primary", None) if diag else None
    return primary or str(exc).strip()
